### ISSUE TITLE
kubernetes deployment + secret을 통한 ssh key 설정

### ISSUE THREAD

**Issue by JaeGeunBang** [JaeGeunBang/dev-tips#13]
### 참고자료
https://stackoverflow.com/questions/39568412/creating-ssh-secrets-key-file-in-kubernetes

**Comment by JaeGeunBang** [comment]
### 개요
- #12 해당 이슈에서 정리한 내용은 kubernetes 환경에서 수행할수 없다.
- kubernetes 환경에서 ssh key를 전달 받기 위해, `deployment + secret`를 활용한다.

### 순서
1. secret을 생성한다.
```
k create secret generic ssh-keys --from-file=id_rsa=/Users/jaegeun/.ssh/id_rsa --from-file=id_rsa.pub=/Users/jaegeun/.ssh/id_rsa.pub
```

2. deployment에 secret을 mount 한다.
```
...
volumes:
  - name: ssh-keys-v
    secret:
      secretName: ssh-keys
      defaultMode: 0600 
  containers:
  - name: ssh-test-container
    image: mySshImage
    volumeMounts:
    - name: ssh-keys-v
      readOnly: true
      # container will see /root/.ssh/id_rsa as usual:
      mountPath: "/root/.ssh"
...
```
3. pod에 접속 후 /root/.ssh 경로에 id_rsa, id_rsa.pub를 활인한다.

**Comment by JaeGeunBang** [comment]
## 특정 키만 mount하고 싶을때

```
volumes:
  - name: ssh-keys-v
    secret:
      secretName: ssh-keys
      defaultMode: 0600 
  containers:
  - name: ssh-test-container
    image: mySshImage
    volumeMounts:
    - name: ssh-keys-v
      readOnly: true
      mountPath: "/root/.ssh/id_rsa"
      subPath: id_rsa
```
